-- `published_sources` cached what a chain publishes about one of its products,
-- fetched by a two-call pipeline that searched for the brand's own page and
-- read one row off it. It lasted a day.
--
-- What replaced it is smaller and better: Google Search is now a *tool* on the
-- recognition call itself, so the model looks the product up while it reads the
-- meal, in one call and in the same schema. Measured on a Subway JP American
-- Clubhouse footlong, published at 698 kcal — the pipeline read 698 for the one
-- chain in seven it could resolve at all, and grounded recognition answers 698
-- for every chain that publishes anywhere a search can see, including the sites
-- the pipeline could not fetch.
--
-- The one thing lost is a URL. `generateContent` returns no grounding metadata
-- beside a response schema, so a grounded figure is an estimate rather than a
-- citation, and the app calls it one.
DROP TABLE IF EXISTS published_sources;
