// The system prompt is generated by `scripts/sync-prompt.mjs` from the file
// under `prompts/` that it names; this module only adds the user turn, which
// depends on whether there is a photograph and therefore cannot live in a
// static file.
export { MEAL_PROMPT_VERSION, MEAL_RECOGNITION_SYSTEM_PROMPT } from "./prompt.generated";

export const MEAL_RECOGNITION_USER_PROMPT = "Read the meal closest to the camera.";

/** The user turn when there is no photograph and the words are the input. */
export const MEAL_RECOGNITION_TEXT_USER_PROMPT =
  "Read the meal described below. There is no photograph; the person's words are the entire input.";
