#!/usr/bin/env node
// One prompt file, one generated constant.
//
// The app and the proxy each used to hold their own copy of the recognition
// prompt as a string literal, and within a day they had drifted: the proxy was
// missing two rules the app had, while both reported the same prompt version.
// Now the phone holds no prompt at all — recognition is something the Worker
// does — and the file under prompts/ is the source the Worker's constant is
// generated from. Tests on the Worker fail when the generated copy falls behind.
//
//   node scripts/sync-prompt.mjs
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const activeVersion = "meal-v28-2026-08-16";
const promptFile = "meal-v28.md";

// The correction prompt has no version of its own: it is not on the evals and
// nothing keys a cache on it. It is generated for the other reason this script
// exists — it had two hand-written copies, and by the time anyone looked they
// had drifted apart in three bullets while both claimed to be the same
// instructions.
const revisionFile = "revision-v6.md";

const prompt = readFileSync(join(root, "prompts", promptFile), "utf8").trimEnd();
const revision = readFileSync(join(root, "prompts", revisionFile), "utf8").trimEnd();

const banner = (file) => `// Generated by scripts/sync-prompt.mjs from prompts/${file}.
// Edit the prompt file and re-run; do not edit this.`;

writeFileSync(
  join(root, "Backend/worker/ai/prompt.generated.ts"),
  `${banner(promptFile)}

export const MEAL_PROMPT_VERSION = ${JSON.stringify(activeVersion)};

export const MEAL_RECOGNITION_SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`,
);

writeFileSync(
  join(root, "Backend/worker/ai/revision.generated.ts"),
  `${banner(revisionFile)}

export const MEAL_REVISION_SYSTEM_PROMPT = ${JSON.stringify(revision)};
`,
);

// Biome formats the generated TypeScript, because the repo's own `check` gate
// does not exempt generated files and `JSON.stringify` emits a single line
// several thousand characters long. Skipped rather than fatal when the
// dependency is not installed.
const biome = join(root, "Backend/node_modules/.bin/biome");
if (existsSync(biome)) {
  execFileSync(
    biome,
    ["check", "--write", "worker/ai/prompt.generated.ts", "worker/ai/revision.generated.ts"],
    { cwd: join(root, "Backend"), stdio: "ignore" },
  );
} else {
  console.warn("biome not installed; generated TypeScript left unformatted");
}

console.log(`synced ${promptFile} (${activeVersion}) and ${revisionFile} into the Worker`);
