#!/usr/bin/env node
// One prompt file, two generated constants.
//
// The app and the proxy each used to hold their own copy as a string literal,
// and within a day they had drifted: the proxy was missing two rules the app
// had, while both reported the same prompt version. Anything downstream — the
// recognition cache, the eval rows, a harness — was therefore comparing答案 to a
// question it could not see. Now the file is the source and both copies are
// generated, with tests on either side that fail when they fall behind.
//
//   node scripts/sync-prompt.mjs
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const activeVersion = "meal-v24-2026-08-12";
const promptFile = "meal-v24.md";

// The correction prompt has no version of its own: it is not on the evals and
// nothing keys a cache on it. It is generated for the other reason this script
// exists — it had two hand-written copies, and by the time anyone looked they
// had already drifted apart in three bullets while both claimed to be the same
// instructions. The taxonomy prose in it is the same prose as above, so a rename
// that reaches one copy and not the other is a model told two different things
// about the same food.
const revisionFile = "revision-v4.md";

const prompt = readFileSync(join(root, "prompts", promptFile), "utf8").trimEnd();
const revision = readFileSync(join(root, "prompts", revisionFile), "utf8").trimEnd();


const banner = (comment) => `${comment} Generated by scripts/sync-prompt.mjs from prompts/${promptFile}.
${comment} Edit the prompt file and re-run; do not edit this.`;

// Swift raw strings need no escaping at all with a # delimiter, which matters:
// the prompt is full of backticks and quotes.
writeFileSync(
  join(root, "Core/Sources/ShamanCore/AI/MealPrompt+Generated.swift"),
  `${banner("//")}

extension MealPrompt {
    public static let version = "${activeVersion}"

    public static let system = #"""
${prompt}
"""#
}
`,
);

writeFileSync(
  join(root, "Backend/worker/ai/prompt.generated.ts"),
  `${banner("//")}

export const MEAL_PROMPT_VERSION = ${JSON.stringify(activeVersion)};

export const MEAL_RECOGNITION_SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`,
);

// Swift multiline literals keep their indentation relative to the closing
// delimiter, so the raw string goes in flush and unindented.
writeFileSync(
  join(root, "Core/Sources/ShamanCore/AI/MealRevisionPrompt+Generated.swift"),
  `${banner("//")}

extension MealRevisionPrompt {
    public static let system = #"""
${revision}
"""#
}
`,
);

writeFileSync(
  join(root, "Backend/worker/ai/revision.generated.ts"),
  `${banner("//")}

export const MEAL_REVISION_SYSTEM_PROMPT = ${JSON.stringify(revision)};
`,
);

// Biome formats the generated TypeScript, because the repo's own `check` gate
// does not exempt generated files and `JSON.stringify` emits a single line
// several thousand characters long. That step used to be a hand-run afterwards,
// which is a step you only remember when a deploy's verify gate stops you —
// which is exactly how it was found. Skipped rather than fatal when the
// dependency is not installed: this script's job is the prompt, and a missing
// linter must not stop the Swift half being written.
const biome = join(root, "Backend/node_modules/.bin/biome");
if (existsSync(biome)) {
  execFileSync(
    biome,
    ["check", "--write", "worker/ai/prompt.generated.ts", "worker/ai/revision.generated.ts"],
    { cwd: join(root, "Backend"), stdio: "ignore" },
  );
} else {
  console.warn("biome not installed; generated TypeScript left unformatted");
}

console.log(
  `synced ${promptFile} (${activeVersion}) and ${revisionFile} into Swift and TypeScript`,
);
