#!/usr/bin/env node
// One prompt file, two generated constants.
//
// The app and the proxy each used to hold their own copy as a string literal,
// and within a day they had drifted: the proxy was missing two rules the app
// had, while both reported the same prompt version. Anything downstream — the
// recognition cache, the eval rows, a harness — was therefore comparing答案 to a
// question it could not see. Now the file is the source and both copies are
// generated, with tests on either side that fail when they fall behind.
//
//   node scripts/sync-prompt.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const activeVersion = "meal-v16-2026-08-07";
const promptFile = "meal-v16.md";

const prompt = readFileSync(join(root, "prompts", promptFile), "utf8").trimEnd();

const banner = (comment) => `${comment} Generated by scripts/sync-prompt.mjs from prompts/${promptFile}.
${comment} Edit the prompt file and re-run; do not edit this.`;

// Swift raw strings need no escaping at all with a # delimiter, which matters:
// the prompt is full of backticks and quotes.
writeFileSync(
  join(root, "Core/Sources/ShamanCore/AI/MealPrompt+Generated.swift"),
  `${banner("//")}

extension MealPrompt {
    public static let version = "${activeVersion}"

    public static let system = #"""
${prompt}
"""#
}
`,
);

writeFileSync(
  join(root, "Backend/worker/ai/prompt.generated.ts"),
  `${banner("//")}

export const MEAL_PROMPT_VERSION = ${JSON.stringify(activeVersion)};

export const MEAL_RECOGNITION_SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`,
);

console.log(`synced ${promptFile} (${activeVersion}) into Swift and TypeScript`);
